### ISSUE TITLE
Problem in installing mirdeep2_0_0_8

### ISSUE THREAD

**Issue by aj03** [lpantano/mirdeep2_core#1]
Hi, I am having problem while installing mirdeep2. Any Solution for this???

perl install.pl
.
.
randfold already installed, nothing to do ...
Compress::Zlib already installed, nothing to do ...
Font::TTf already installed, nothing to do ...
PDF::API2 already installed, nothing to do ...

RNAfold was/is not installed properly
()

When i am running tutorial_dir/run_tut.sh its working properly but when running mirdeep2.pl for my data its throwing error (RNAfold error)

report.log:
computing randfold p-values select_for_randfold.pl mirdeep_runs/run_17_11_2016_t_14_17_29/tmp/signature.arf mirdeep_runs/run_17_11_2016_t_14_17_29/tmp/precursors.str > mirdeep_runs/run_17_11_2016_t_14_17_29/tmp/precursors_for_randfold.ids
started: 14:19:59
Use of uninitialized value $lng in numeric le (<=) at /opt/mirdeep2_0_0_8/src/select_for_randfold.pl line 266, <filename> line 118.
Use of uninitialized value in numeric le (<=) at /opt/mirdeep2_0_0_8/src/select_for_randfold.pl line 686, <filename> line 118.
Use of uninitialized value in numeric le (<=) at /opt/mirdeep2_0_0_8/src/select_for_randfold.pl line 714, <filename> line 118.
Use of uninitialized value in numeric le (<=) at /opt/mirdeep2_0_0_8/src/select_for_randfold.pl line 686, <filename> line 118.
..
.
.

error.log:
RNAfold: invalid option -- n

I tried with Sample Installation too...by downloading all necessary packages required ()
a     bowtie short read aligner (http://bowtie-bio.sourceforge.net/index.shtml)
b     Vienna package with RNAfold (http://www.tbi.univie.ac.at/~ivo/RNA/)
c.i   SQUID library (http://selab.janelia.org/software.html) goto Squid and download it
c.ii  randfold (http://bioinformatics.psb.ugent.be/software/details/Randfold)
d     Perl package PDF::API2 (http://search.cpan.org/search?query=PDF%3A%3AAPI2&mode=all)

**Comment by lpantano** [comment]
Hi,

sorry about the issue. Actually this repo is used to create a bioconda package and ready to use through bioconda. That error seems to be a problem with rnafold version. 

Can you tell me what version you have? maybe it is a question to update the command used inside the code.

I am out of town so I will look at this on Monday.

Cheers

sent not from my computer

**Comment by aj03** [comment]
Hi,
When i am locating RNAFold version its showing this:

$locate RNAfold
/opt/ViennaRNA-2.3.0/src/bin/RNAfold
/opt/mirdeep2_0_0_8/essentials/ViennaRNA-1.8.4/Progs/RNAfold
/usr/local/bin/RNAfold

$RNAfold -V
RNAfold 2.3.0

**Comment by lpantano** [comment]
Hi,

Did you find something else? I tried to reproduce but it is difficult since it seems depend on the data.

**Comment by aj03** [comment]
Hi,
Thanks lpantano. 
I have resolved this error.
The RNAFold version which I had in /usr/local/bin was /opt/ViennaRNA-2.3.0/src/bin/RNAfold but mirdeep2 install.pl requires /opt/mirdeep2_0_0_8/essentials/ViennaRNA-1.8.4/ version. As soon as I changed it,it started working.

perl install.pl
###############################################################################################
# Last update: May 18, 2016
# This is the miRDeep2 installer. 
# It is tested under a bash and zsh shell
# It will try to download all necessary files and install them. 
#
###############################################################################################
gcc version: 4.8.4-2ubuntu1~14.04.3)                                      already installed, nothing to do ...
Checking environment variables ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 82714  100 82714    0     0  36581      0  0:00:02  0:00:02 --:--:-- 36582
bowtie                                           already installed, nothing to do ...
RNAfold                                          already installed, nothing to do ...
randfold					 already installed, nothing to do ...
Compress::Zlib					 already installed, nothing to do ...
Font::TTf                                        already installed, nothing to do ...
PDF::API2                                        already installed, nothing to do ...

Installation successful

**Comment by lpantano** [comment]
perfect!

**Comment by shashj199** [comment]
Hey, 

I am getting the same error. But when I try to install, Vienna 1.8.4 it throws an error

```
gcc  -g -O2   -o RNAfold RNAfold.o ../lib/libRNA.a -lm 
Undefined symbols for architecture x86_64:
  "_HairpinE", referenced from:
      _fill_arrays in libRNA.a(libRNA_a-fold.o)
      _backtrack in libRNA.a(libRNA_a-fold.o)
      _circfold in libRNA.a(libRNA_a-fold.o)
      _stack_energy in libRNA.a(libRNA_a-fold.o)
      _energy_of_circ_struct in libRNA.a(libRNA_a-fold.o)
      _loop_energy in libRNA.a(libRNA_a-fold.o)
  "_LoopEnergy", referenced from:
      _fill_arrays in libRNA.a(libRNA_a-fold.o)
      _backtrack in libRNA.a(libRNA_a-fold.o)
      _circfold in libRNA.a(libRNA_a-fold.o)
      _stack_energy in libRNA.a(libRNA_a-fold.o)
      _energy_of_circ_struct in libRNA.a(libRNA_a-fold.o)
      _loop_energy in libRNA.a(libRNA_a-fold.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [RNAfold] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
Output of RNAfold -V

```
RNAfold 2.3.5
```

Can you help me in installing Vienna 1.8.4?

Thanks

**Comment by lpantano** [comment]
Hi,

sorry to hear you have issues. I use conda environment to install all tools, so not sure what is going on here. 

Any chance you can move to a conda environment and use bioconda to install the vienna suit?
