### ISSUE TITLE
mirdeep2 - Unknown option: f

### ISSUE THREAD

**Issue by miasteinberg** [lpantano/mirdeep2_core#2]
Hello! I installed bcbio and have upgraded with bcbio_nextgen.py upgrade --genomes hg19. Running through the small RNA example pipeline, I am getting an error at the miRDeep2 step:

```
#Starting miRDeep2
/path/to/bcbio/anaconda/bin/miRDeep2.pl /mnt/nfs/gigantor/ifs/DCEG/path/to/smallrna_test/mirqc_bcbio/work/mirdeep2/file_reads.fa /mnt/nfs/gigantor/ifs/DCEG/path/to/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa /mnt/nfs/gigantor/ifs/DCEG/path/to/smallrna_test/mirqc_bcbio/work/mirdeep2/align.bam /path/to/bcbio/genomes/Hsapiens/hg19/srnaseq/mature.fa
 none /path/to/bcbio/genomes/Hsapiens/hg19/srnaseq/hairpin.fa -f /path/to/bcbio/genomes/Hsapiens/hg19/srnaseq/Rfam_for_miRDeep.fa -r simple -c -P -t h
sa -z res

miRDeep2 started at 17:27:17

Unknown option: f
mkdir mirdeep_runs/run_17_01_2017_t_17_27_17

#Starting miRDeep2
Error:   Rfam_for_miRDeep.fa not found in your miRDeep2 scripts directory
Please copy this file from the miRDeep2 archive to your miRDeep2 directory

' returned non-zero exit status 2
[2017-01-17T22:27Z] mirdeep2 failed. Please report the error to https://github.com/lpantano/mirdeep2_core/issues.
```

I noticed that the code in this repo has an -f option added that the original mirdeep does not, so I double checked which version of mirdeep I was using, but it looks correct:

```
[steinbergmk@node041 work]$ which miRDeep2.pl
/path/to/bcbio/anaconda/bin/miRDeep2.pl
```

The code in this repo is mirdeep 2.0.0.7 while the mirdeep packaged with bcbio is 2.0.0.8. Do I need to roll back to 2.0.0.7 somehow?

Thanks much,
Mia

**Comment by lpantano** [comment]
Yes, please, install mirdeep 2.0.0.7, I will fix the dependency for bcbio to avoid future problems.

Let me know if that fix it! Thanks!

**Comment by lpantano** [comment]
You can do this by using conda from bcbio installation:

`conda install -f mirdeep2=2.0.0.7 -c bioconda`

**Comment by miasteinberg** [comment]
That fixed the problem, thanks!
