### ISSUE TITLE
error to crash the whole analysis

### ISSUE THREAD

**Issue by lpantano** [lpantano/mirdeep2_core#3]
No file mirdeep_runs/run_res/tmp/precursors.fa_stack found

**Comment by rdocking** [comment]
Noting that I saw this one just now using the latest bcbio (1.1.5a):

```
[2019-04-06T01:04Z] n125: No file mirdeep_runs/run_res/tmp/precursors.fa_stack found
[2019-04-06T01:04Z] n125: Uncaught exception occurred
Traceback (most recent call last):
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset PERL5LIB && export PATH=/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/bin:"$PATH" && perl /projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/bin/miRDeep2.pl /projects/karsanscratch/rdocking/KARSANBIO-1672_reprocessing/aml_pmp_mirna/work/mirdeep2/file_reads.fa /projects/rdocking_prj/software/bcbio-nextgen/data/genomes/Hsapiens/hg19/seq/hg19.fa /projects/karsanscratch/rdocking/KARSANBIO-1672_reprocessing/aml_pmp_mirna/work/mirdeep2/align.bam /projects/rdocking_prj/software/bcbio-nextgen/data/genomes/Hsapiens/hg19/srnaseq/mature.fa none /projects/rdocking_prj/software/bcbio-nextgen/data/genomes/Hsapiens/hg19/srnaseq/hairpin.fa -f /projects/rdocking_prj/software/bcbio-nextgen/data/genomes/Hsapiens/hg19/srnaseq/Rfam_for_miRDeep.fa -r simple -c -P -t hsa -z res
```

I don't recall seeing this when I ran fewer samples, so maybe this is a memory issue.

**Comment by lpantano** [comment]
hi,

thanks for reporting this. I couldn't figure out what was going on here. If you run this locally in python inside a single job with more memory, it will crash as well?. You may need to remove mirdeep folder before restarting.

Thanks!

**Comment by rdocking** [comment]
Hi @lpantano  - I did some digging on this today and I think it's related to this issue in the parent repo:

https://github.com/rajewsky-lab/mirdeep2/issues/17

I too noticed this hard-coded variable in `excise_precursors_iterative_final.pl`

`my $upper_bound=50`

As I understand it, if there are more than 50 precursors, the program stops. As a workaround, we could either:

- Update the value to a higher number (I just tried setting it to 500, and my run of ~250 libraries completed when it hit 193 precursors
- Use the `-g 1` parameter in the initial mirdeep2 call

Thoughts? Thanks for looking into this!

**Comment by rdocking** [comment]
The parameter to set is actually `-g -1`, since the check is:

`if($thres_counts{$z} < $pres_max or $pres_max < 0){`

https://github.com/lpantano/mirdeep2_core/blob/0e96444370683a1f5eeb4a5c0a85dc118ec0c01d/excise_precursors_iterative_final.pl#L69

Should I submit a PR on the bcbio side for this? Setting this parameter lets me get past the previous error.

**Comment by lpantano** [comment]
Please, make the PR, this is very useful.

Thanks!

On April 8, 2019 at 6:29:45 PM, Rod Docking (notifications@github.com)
wrote:

The parameter to set is actually -g -1, since the check is:

if($thres_counts{$z} < $pres_max or $pres_max < 0){

https://github.com/lpantano/mirdeep2_core/blob/0e96444370683a1f5eeb4a5c0a85dc118ec0c01d/excise_precursors_iterative_final.pl#L69

Should I submit a PR on the bcbio side for this? Setting this parameter
lets me get past the previous error.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/lpantano/mirdeep2_core/issues/3#issuecomment-481031871>,
or mute the thread
